services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "$METUBE_PORT:8081"
    volumes:
      - $DATADIR/downloads/metube:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      # - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.metube-rtr.entrypoints=websecure"
      - "traefik.http.routers.metube-rtr.rule=Host(`metube.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.metube-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=$METUBE_PORT"
