services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - t3_proxy
    # Don't expose Plex's port to the host, as Traefik will handle routing and SSL termination. 
    # This enhances security by keeping Plex's interface inaccessible directly from the outside.
    # ports:
    #   - "32400:32400"
    volumes:
      - ${DOCKERDIR}/appdata/plex:/config
      - ${DATADIR}/plex_library:/media
      - /dev/shm:/transcode
    environment:
      PLEX_UID: ${PUID}
      PLEX_GID: ${PGID}
      TZ: ${TZ}
      HOSTNAME: ${HOSTNAME}
      PLEX_CLAIM_FILE: "/run/secrets/plex_claim"
      ADVERTISE_IP: "https://plex.${DOMAINNAME}:443"
    secrets:
      - plex_claim
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plexms-rtr.entrypoints=websecure"
      - "traefik.http.routers.plexms-rtr.rule=Host(`plex.$DOMAINNAME`)"
      - "traefik.http.routers.plexms-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.plexms-rtr.middlewares=chain-no-auth@file"
      ## HTTP Servicesnoauth
      - "traefik.http.routers.plexms-rtr.service=plexms-svc"
      - "traefik.http.services.plexms-svc.loadbalancer.server.port=32400"
