services:
  kavita:
    container_name: kavita
    image: lscr.io/linuxserver/kavita:latest
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - $KAVITA_PORT:5000
    volumes:
      - $DOCKERDIR/appdata/kavita:/config
      - $DATADIR/ebooks:/data/ebooks
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      # - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.kavita-rtr.entrypoints=websecure"
      - "traefik.http.routers.kavita-rtr.rule=Host(`kavita.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.kavita-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.kavita-rtr.service=kavita-svc"
      - "traefik.http.services.kavita-svc.loadbalancer.server.port=$KAVITA_PORT"
