########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
include:
  # SERVICES
  # PREFIX smg = Saber Media Group
  # ################################################
  # CORE
  - utils/socket-proxy/docker-compose.yml
  - utils/traefik2/docker-compose.yml
  - utils/portainer/docker-compose.yml
  # ################################################
  # SECURITY
  - utils/crowdsec/docker-compose.yml
  - utils/crowdsec/traefik-bouncer.yml
  - utils/crowdsec/cloudflare-bouncer.yml
  # ################################################
  # DASHBOARD - FRONTEND
  # - utils/homepage/docker-compose.yml
  # ################################################
  # APPS
  - apps/vaultwarden/docker-compose.yml
  - apps/plex/docker-compose.yml
  - apps/ebooks/kavita/docker-compose.yml
  - apps/ebooks/lazylibrarian/docker-compose.yml
  - apps/filebrowser/docker-compose.yml
  # ################################################
  # DOWNLOADERS
  - apps/downloaders/qbittorrent/docker-compose.yml
  - apps/downloaders/sabnzd/docker-compose.yml
  - apps/downloaders/metube/docker-compose.yml
  # ################################################
  # PVRS
  - apps/pvrs/radarr/docker-compose.yml
  - apps/pvrs/sonarr/docker-compose.yml
  - apps/pvrs/bazarr/docker-compose.yml
  - apps/pvrs/lidarr/docker-compose.yml
  - apps/pvrs/prowlarr/docker-compose.yml
  # TODO: LOOK FOR ALTERNATIVE TO PICARD
  # - apps/pvrs/picard/docker-compose.yml 
  # ################################################
  # MONITORING
  - utils/uptime-kuma/docker-compose.yml
  - utils/dozzle/docker-compose.yml
  # ################################################
  # MAINTENANCE
  # ################################################
  # DEV TOOLS
  # ################################################
