########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token

include:
  ########################### SERVICES
  # PREFIX smg = Saber Media Group

  # CORE
  - utils/socket-proxy/docker-compose.yml
  - utils/traefik2/docker-compose.yml
  - utils/portainer/docker-compose.yml
  #
  # SECURITY, ANALYTICS, METRICS, LOGS, MONITORING
  # - utils/crowdsec/docker-compose.yml
  # - utils/dozzle/docker-compose.yml
  #
