services:
  # Uptime Kuma - Status Page & Monitoring Server
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "3001:3001"
    volumes:
      - $DOCKERDIR/appdata/uptime-kuma:/app/data
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.uptime-kuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma-rtr.rule=Host(`kuma.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.uptime-kuma-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.uptime-kuma-rtr.service=uptime-kuma-svc"
      - "traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001"
