version: '3'

services:
  db:
    image: postgres:11
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=$PG_PWD
    networks:
      - nextcloud
  
  redis:
    image: redis:6.2-alpine
    container_name: nextcloud_redis
    command: redis-server --requirepass $REDIS_PWD
    restart: unless-stopped
    networks:
      - nextcloud

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8088:80
    volumes:
      - $DOCKERDIR/appdata/nextcloud/data:/var/www/html # Change this to where you would like Nextcloud data (preferably external storage)
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=$PG_PWD
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=$REDIS_PWD
      - NEXTCLOUD_TRUSTED_DOMAINS=$NC_DOMAIN
    depends_on:
      - db
      - redis
    networks:
      - nextcloud
      - npm_proxy
      
networks:
  nextcloud:
    driver: bridge
  npm_proxy:
    external: true