services:
  docket-socket-proxy:
    image: "tecnativa/docker-socket-proxy"
    container_name: "docker-socket-proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "2375:2375"
    environment:
      - CONTAINERS=1
