services:
  # Picard - Music Library Tagging and Management
  picard:
    image: mikenye/picard:latest
    container_name: picard
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "$PICARD_PORT:5800"
    volumes:
      - $DATADIR/staging/music:/data/music:rw
      - $DOCKERDIR/appdata/picard:/config:rw
      - /dev/shm:/dev/shm
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 2
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
    labels:
      # - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.picard-rtr.entrypoints=websecure"
      - "traefik.http.routers.picard-rtr.rule=Host(`picard.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.picard-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.picard-rtr.service=picard-svc"
      - "traefik.http.services.picard-svc.loadbalancer.server.port=$PICARD_PORT"
