services:
  # File Browser - Explorer
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "$FILEBROWSER_PORT:80"
    volumes:
      - $DATADIR:/srv
      - $DOCKERDIR/appdata/filebrowser/data/filebrowser.db:/database/filebrowser.db
      - $DOCKERDIR/appdata/filebrowser/config/settings.json:/config/settings.json
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      # - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=websecure"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`fb.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=$FILEBROWSER_PORT"
