services:
  lazylibrarian:
    container_name: lazylibrarian
    image: lscr.io/linuxserver/lazylibrarian:latest
    restart: unless-stopped
    ports:
      - $LAZYLIBRARIAN_PORT:5299
    volumes:
      - $DOCKERDIR/appdata/lazylibrarian:/config
      - $DATADIR/staging/ebooks:/data/downloads
      - $DATADIR/ebooks:/data/ebooks
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    labels:
      # - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.lazylibrarian-rtr.entrypoints=websecure"
      - "traefik.http.routers.lazylibrarian-rtr.rule=Host(`lazylibrarian.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.lazylibrarian-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.lazylibrarian-rtr.service=lazylibrarian-svc"
      - "traefik.http.services.lazylibrarian-svc.loadbalancer.server.port=$LAZYLIBRARIAN_PORT"
