version: '3'
services:
  portainer:
    container_name: portainer
    ports:
      - '8000:8000'
      - '9443:9443'
    restart: always
    volumes:
      - ${DOCKERDIR}/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    image: portainer/portainer-ce:latest
    environment:
      TZ: ${TZ}
    networks:
      npm_proxy:
        ipv4_address: 10.2.0.253
networks:
  npm_proxy:
    external: true


