services:
  # CrowdSec Bouncer - Cloudflare
  # NOTE: Set max ip number right the first time (max 10000). Recreating container deletes all ips and readds them causing cloudflare 429 rate limiting.
  cloudflare-bouncer:
    container_name: cloudflare-bouncer
    image: crowdsecurity/cloudflare-bouncer:v0.2.1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - 2112:2112
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/crowdsec/cloudflare-bouncer/cfg.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml     