services:
  # CrowdSec - Open-source & collaborative security IPS
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:v1.6.1-2
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "$CROWDSEC_API_PORT:8080"
      - "$CROWDSEC_PROMETHEUS_EXPORT:6060"
    environment:
      #this is the list of collections we want to install
      #https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/sshd"
      GID: "${GID-1000}"
      CUSTOM_HOSTNAME: "smg"
    volumes:
      - ${DOCKERDIR}/logs:/logs:ro
      - /var/log:/var/log:ro
      - ${DOCKERDIR}/appdata/crowdsec/data:/var/lib/crowdsec/data
      - ${DOCKERDIR}/appdata/crowdsec/config:/etc/crowdsec
